delete_merged_branches = true
update_base_for_deletes = true

# needs to remain squash for current release process
use_squash_merge = true

status = [
	"Test with Rust nightly",
	"Test with Rust stable",
	"Test with Rust 1.63.0",
]

# Disabled until https://github.com/bors-ng/bors-ng/issues/1434 is fixed
#pr_status = [
#	"PR check (clippy)",
#]
