allow-branch = ["main"]
consolidate-pushes = true
push-options = ["--follow-tags"]
push-remote = "git@github.com:passcod/citeworks.git"
sign-tag = true
sign-commit = true
tag-name = "{{prefix}}-{{version}}"
