[package]
name = "citeworks-csl"
version = "0.1.0"
edition = "2021"

[dependencies]
decorum = { version = "0.3.1", default-features = false }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
thiserror = "1.0.32"
