name: PR checks

on:
  pull_request:

jobs:
  check:
    name: PR check (clippy)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default 1.59.0
          rustup component add clippy
      - run: cargo clippy
