name: Main branch

on:
  push:
    branches:
      - main
    tags-ignore:
      - "*"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configure toolchain
        run: |
          rustup toolchain install --profile minimal --no-self-update stable
          rustup default stable
      - run: cargo check
